In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer
import torch
import numpy as np


In [2]:
df = pd.read_excel('Kitap2.xlsx')

In [3]:
questions = df['Questions'].tolist()
answers = df['Answer'].tolist()

In [4]:
model = SentenceTransformer('bert-base-nli-mean-tokens')

In [5]:
questions_encoded = model.encode(questions)
answers_encoded = model.encode(answers)

In [6]:
questions_tensor = torch.from_numpy(questions_encoded)
answers_tensor = torch.from_numpy(answers_encoded)

In [7]:
import torch
import torch.nn as nn

# Define the model
class DNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)  # Add a softmax layer
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        x = self.softmax(x)  # Apply the softmax function
        return x

# Initialize the model
input_size = questions_tensor.size(-1)
output_size = answers_tensor.size(-1)
hidden_size = 32
model = DNN(input_size, hidden_size, output_size)

# Define the loss function and the optimizer
loss_fn = torch.nn.CrossEntropyLoss()  # Use the cross-entropy loss functionloss_fn = torch.nn.CrossEntropyLoss()  # Use the cross-entropy loss function
optimizer = torch.optim.Adam(model.parameters())

# Train the model
for epoch in range(10):
    # Forward pass
    logits = model(questions_tensor)
    loss = loss_fn(logits, answers_tensor)

    # Backward pass
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

In [8]:
model = torch.nn.Sequential(
    torch.nn.Linear(questions_tensor.size(-1), answers_tensor.size(-1)),  # change the number of input units to match the number of rows in the questions tensor
    torch.nn.ReLU(),
    torch.nn.Linear(answers_tensor.size(-1), 1)
)

In [9]:
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters())

In [10]:
for epoch in range(500):
    # Forward pass
    logits = model(questions_tensor)
    loss = loss_fn(logits, answers_tensor)

    # Backward pass
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

c:\Users\berka\anaconda3\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([396, 768])) that is different to the input size (torch.Size([396, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [11]:
# Load the SentenceTransformer model
sentence_transformer = SentenceTransformer('bert-base-nli-mean-tokens')

# Encode the input question using the SentenceTransformer model
input_question = "I wanna go bathroom"
input_question_encoded = sentence_transformer.encode([input_question])

# Convert the NumPy array to a PyTorch tensor
input_question_tensor = torch.from_numpy(input_question_encoded)

# Make a prediction using the PyTorch model
prediction = model(input_question_tensor)

# Print the prediction
print(prediction)

tensor([[-0.0189]], grad_fn=<AddmmBackward0>)


In [12]:
# Make a prediction using the PyTorch model
prediction = model(input_question_tensor)

# Get the index of the highest prediction
prediction_index = torch.argmax(prediction).item()

# Get the corresponding answer from the list of answers
prediction_string = answers[prediction_index]

# Print the prediction
print(prediction_string)

On the work table in the living room.


In [13]:
# Encode the list of answers using the SentenceTransformer model
answers_encoded = sentence_transformer.encode(answers)

# Convert the encoded answers into a tensor
answers_tensor = torch.from_numpy(answers_encoded)

# Initialize a counter for the number of correct predictions
correct_predictions = 0

# Iterate over the list of questions
# Iterate over the list of questions
for question, answer in zip(questions, answers):
    # Encode the question using the SentenceTransformer model
    question_encoded = sentence_transformer.encode([question])
    
    # Convert the encoded question into a tensor
    question_tensor = torch.from_numpy(question_encoded)
    
    # Make a prediction using the PyTorch model
    prediction = model(question_tensor)
    
    # Get the index of the highest prediction
    prediction_index = torch.argmax(prediction).item()
    
    # Get the corresponding answer from the list of answers
    prediction_string = answers[prediction_index]
    
    # Check if the prediction is correct
    if prediction_string == answer:
        # Increment the counter for correct predictions
        correct_predictions += 1

# Calculate the accuracy of the model
accuracy = correct_predictions / len(questions)

# Print the accuracy
print(accuracy)


0.012626262626262626


In [14]:
# Encode the answer using the SentenceTransformer model
answer_encoded = sentence_transformer.encode([answer])

# Convert the encoded answer into a tensor
answer_tensor = torch.from_numpy(answer_encoded)

# Calculate the cosine similarity between the prediction and the answer
similarity = nn.CosineSimilarity(dim=1)(prediction, answer_tensor)
if similarity > 0.8:
    # Increment the counter for correct predictions
    correct_predictions += 1
# Calculate the accuracy of the model
accuracy = correct_predictions / len(questions)

# Print the accuracy
print(accuracy)

0.012626262626262626


In [74]:
random_user = df['Questions'].sample(10, random_state=25)

In [75]:
random_user = random_user.tolist()

In [76]:
random_user

['How is it going',
 'I am looking comb.',
 'Where is the counter?',
 'Can you tell me, where can ı find the medicine?',
 'Where is the glasses?',
 'Do you know where is the cloakroom?',
 'Do you know where is the pyjamas?',
 'Can you tell me, where can ı find the fabric softener?',
 'I am looking bakery.',
 'Can you tell me, How can ı go to Bathroom from the Bedroom?']

In [65]:
input_question_encoded = sentence_transformer.encode(random_user)

In [66]:
input_question_encoded

array([[ 8.45502198e-01,  4.19052511e-01,  2.39110565e+00,
         2.63466418e-01,  6.52291924e-02, -3.59421015e-01,
         1.34788275e+00, -2.92608351e-01,  6.76919520e-01,
        -2.86102921e-01, -1.02284515e+00,  2.31712297e-01,
         3.43854398e-01,  6.66127026e-01,  3.13239902e-01,
        -3.31460625e-01,  2.23493919e-01, -3.28229964e-01,
         1.26276767e+00,  4.98485938e-03, -1.73984766e-01,
         2.57861465e-01, -3.97199154e-01, -6.63901269e-01,
        -3.22171956e-01,  4.34838802e-01,  1.40895143e-01,
         4.56119686e-01, -1.04766095e+00, -3.96824121e-01,
         2.39548042e-01, -1.30176261e-01,  3.95919472e-01,
        -4.02382463e-01,  2.95519829e-01,  7.87561953e-01,
        -2.57563204e-01,  3.67773443e-01,  2.78422236e-01,
        -2.03746423e-01, -5.63988946e-02,  9.98828486e-02,
         6.50295317e-01, -4.19358760e-01, -6.19155169e-01,
         1.89833026e-02,  6.97368324e-01,  1.12973444e-01,
        -3.08396220e-01, -9.28729236e-01, -4.05708075e-0

In [67]:
input_question_tensor = torch.from_numpy(input_question_encoded)

In [68]:
prediction = model(input_question_tensor)

In [69]:
print(prediction)

tensor([[-0.0189]], grad_fn=<AddmmBackward0>)
